### ISSUE TITLE
Constraints do not always preserve number of elements

### ISSUE THREAD

**Issue by pjbulls** [jwood000/RcppAlgos#41]
I'm using permuteGeneral to generate all permutations for N subjects to be distributed across M categories, which requires the constraint that the sum of all elements is N. However, adding such constraint reduces the dimension of the output, where it does not seem to consider zeroes in different positions as unique permutations:

```r
permuteGeneral(v = 0:2, m = 3, repetition = TRUE) 
## Works, but needs constraint (only desired rows shown)
      [,1] [,2] [,3]
 [3,]    0    0    2
 [5,]    0    1    1
 [7,]    0    2    0
[11,]    1    0    1
...

permuteGeneral(v = 0:2, m = 3, repetition = TRUE, constraintFun = "sum", comparisonFun = "==", limitConstraints = 2)
## No longer returns 3-element permutations?
     [,1] [,2]
[1,]    0    2
[2,]    2    0
[3,]    1    1
```

Is this intended behaviour?

**Comment by jwood000** [comment]
@pjbulls,

I apologize for the late reply. What version of `RcppAlgos` do you have?

The current version gives more consistent results. As is outlined in many places (vignettes, man files, NEWS, etc.), `permuteGeneral`, when constrained, will not be in lexicographical order.

``` r
library(RcppAlgos)
packageVersion("RcppAlgos")
#> [1] '2.7.2'

permuteGeneral(v = 0:2, m = 3,
               repetition = TRUE,
               constraintFun = "sum",
               comparisonFun = "==",
               limitConstraints = 2)
#>      [,1] [,2] [,3]
#> [1,]    0    0    2
#> [2,]    0    2    0
#> [3,]    2    0    0
#> [4,]    0    1    1
#> [5,]    1    0    1
#> [6,]    1    1    0
```

It looks like you are looking for integer compositions. As of version `2.6.0`, we have a family of `composition` funcitons. For example:

``` r
compositionsGeneral(v = 0:2, repetition = TRUE)
#>      [,1] [,2]
#> [1,]    0    2
#> [2,]    1    1
```

Note, if you try to get compositions of greater length, the output will not change.

``` r
compositionsGeneral(v = 0:2, m = 3, repetition = TRUE)
#>      [,1] [,2]
#> [1,]    0    2
#> [2,]    1    1
```

This is intentional. Per the wikipedia article on [compositions](https://en.wikipedia.org/wiki/Composition_(combinatorics)), zeros do not have any impact on standard compositions. That is, the following two compositions are identical:

``` r
c(0, 2)
#> [1] 0 2
c(0, 0, 0, 2)
#> [1] 0 0 0 2
```

You will note that if you keep reading, you will come across the term **weak composition** which allows zero to be a part of the sequence. In `RcppAlgos`, the composition funtions have a parameter called `weak`, which allows one to explore these compositions:

``` r
compositionsGeneral(v = 0:2, m = 3, repetition = TRUE, weak = TRUE)
#>      [,1] [,2] [,3]
#> [1,]    0    0    2
#> [2,]    0    1    1
#> [3,]    0    2    0
#> [4,]    1    0    1
#> [5,]    1    1    0
#> [6,]    2    0    0
```

Note the output is slightly different than that of `permuteGeneral` above. The output of `compositionGeneral` is in lexicographical order.

Lastly, here is a [NEWS entry](https://github.com/jwood000/RcppAlgos/blob/main/NEWS.md#other-6) addressing this issue.

I hope this helps!

Thanks,
Joseph

**Comment by pjbulls** [comment]
Thank you for the detailed info! For posterity, I was indeed on an older version (2.4.1) as we are still on R3.6 and don't seem to have C++17 support either, so the lazy default was the pre-compiled Windows CRAN binary.

The weak composition (or updated `permuteGeneral`) looks like what we need, order is not so important but zeroes always being part of a sequence is. Should have read the docs, I'll go bug our IT guy to support a more recent version. Thanks again!
