### ISSUE TITLE
Basic unranking

### ISSUE THREAD

**Issue by moorembioinfo** [jwood000/RcppAlgos#47]
Hi, I was following your instructions here (https://stackoverflow.com/questions/73992417/itertools-combinations-find-if-a-combination-is-divisible) and I'm losing the order of the combinations, is this expected? i.e.:

```
comb =c(78, 45, 21, 100, 74, 38, 22, 22, 85, 78, 45)
idx <- comboRank(comb, v = 100, repetition=TRUE)
check_comb = comboSample(100, 11, sampleVec = idx, repetition=TRUE)
identical(as.vector(check_comb), comb)

> comb
 [1]  78  45  21 100  74  38  22  22  85  78  45
> as.vector(check_comb)
 [1]  21  22  22  38  45  45  74  78  78  85 100
```

Is there a way to unrank _idx_ and recover _comb_ including the order

**Comment by jwood000** [comment]
Hello @moorembioinfo,

If order is important, you shouldn't be looking at combinations as, by definition, order doesn't matter. If you need to preserve the order, you need tools that deal with permutations.

You are in luck! In `RcppAlgos`, for every combination specific function, there is a permutation counterpart. E.g.

```r
perm = as.integer(c(78, 45, 21, 100, 74, 38, 22, 22, 85, 78, 45))
idx <- permuteRank(perm, v = 100, repetition=TRUE)
check_perm = permuteSample(100, 11, sampleVec = idx, repetition=TRUE)
identical(as.vector(check_comb), comb)
#> TRUE

perm
#> [1] 78  45  21 100  74  38  22  22  85  78  45
as.vector(check_comb)
#> [1]  78  45  21 100  74  38  22  22  85  78  45
```

Note, since order matters, the number of results is huge.

```r
idx
#> Big Integer ('bigz') :
#> 7744209973372121847745
```

The algorithms in `RcppAlgos` are very efficient and handle this case with no problems.

I hope this helps!

Joseph
